### ISSUE TITLE
Scrum Report Jun 10th

### ISSUE THREAD

**Issue by sroyracha** [min2028/GuardNav#17]

**Comment by sroyracha** [comment]
Name: Ryosuke Urawa
CSID: c5w7t

What did you work on this past iteration (2 weeks)?
I worked on Figma and created `about page`, `landing page`, and updated `map page`. I also worked on creating navbar component and pushed some commits to fix minor bugs.
 
What were any major issues/challenges you ran into?
The main challenge was `npm start` command working. I ran into some issues with installing required packaged but `npm install` didn't work and I had to use `yarn` instead.

What do you plan to work on for this coming iteration (2 weeks)?
For the coming iteration, I'll be putting initial data (the destination of the trip) in the map page, and start implementing a logic to plan a trip based on the criminal data we will be plotting on the map.

**Comment by seiyoung-lee** [comment]
Name: Andres Lee
CSID: r1m2b

What did you work on this past iteration (2 weeks)?
I worked on the cards that show the potential routes and we will use those cards as well for the history portion.

What were any major issues/challenges you ran into?
There was some miscommunication between teammates and we made components that are similar, but we fixed that after talking.

What do you plan to work on for this coming iteration (2 weeks)?
I plan on tidying up the styling and implement the landing page for our app. I will also be working on the different front-end functionality that we haven't finished from the past iteration.

**Comment by kmdicksn** [comment]
Name: Dickson Ngan
CSID: l5x2b

What were any major issues/challenges you ran into?
1. What did you work on this past iteration (2 weeks)?
I worked mostly with integrating Google Map's API and helped design the map page this past iteration. This included the main map component, search bar with autocomplete, and tracking the user's geolocation and saving it via Redux. I also added a component for displaying the current weather information to the user using the user's geolocation and OpenWeather's API.

2. What were any major issues/challenges you ran into?
Incorporating the Google Maps API presented a major challenge as I had no prior experience with it.

3. What do you plan to work on for this coming iteration (2 weeks)?
For the coming iteration, I intend to further flesh out the design of our project as well as creating the route planning page with the route visualization on the map.

**Comment by min2028** [comment]
Name: Aung Khant Min
CSID: d9p3n

What did you work on this past iteration (2 weeks)?
I worked on creating a side nav bar on the map page which is a drawer that transition the elements around when opened. I also created a theme for the app. 

What were any major issues/challenges you ran into?
Material UI is a technology that I do not have experience with so it took more time to finish the component. The technologies used takes some time to become accustomed to.

What do you plan to work on for this coming iteration (2 weeks)?
For the coming iteration, I plan to initialize MongoDB,  perform data modelling and populate them with the crime data.

**Comment by AayushRaghuvamshi** [comment]
Name: Aayush Raghuvamshi
CSID: v5x2b

What did you work on this past iteration (2 weeks)?
I worked on creating several components which served to display trips in a drop down trip list, and I used redux to have an initial state.

What were any major issues/challenges you ran into?
There was some miscommunication between teammates that made merge requests a little difficult, and it also resulted in some redundancy in components.

What do you plan to work on for this coming iteration (2 weeks)?
I'm planning to implement a heatmap overlay by feeding the Google maps API some VPD sourced crime data on which I'll first do a fair bit of data processing.
